---
title: "R tutorial"
format: html
editor: visual
bibliography: References.bib
csl: vancouver.csl
---

## Testing av referanser

Dette blir bra @billatOxygenKineticsModelling2000! Muligens vanskelig @bossiOptimizingIntervalTraining2020.

## Scatterplot av alle deltakere i Boston marathon 2019

```{r}
#| echo: false
#| warning: false
#| message: false
library(exscidata)
library(tidyverse)


  exscidata::boston |>
  filter(year == 2019) |>
  
  ggplot(aes(x = age, y = seconds)) +
    geom_point()

```


Lekser uke 40

Oppgave 14

```{r}
#| echo: true
#| message: false
#| warning: false

library(tidyverse)
library(exscidata)

Oppgave14 <-strengthvolume %>% 
  filter(time %in% c("session1", "post"), 
  exercise == "legpress") %>% 
  mutate(time = factor(time, levels = c("session1", "post"))) %>% 
  ggplot(aes(x = time, y = load)) + 
  geom_point(size = 2) +
  facet_wrap(~ sets)

Oppgave14

```

Oppgave 15

```{r}
#| echo: true
#| message: false
#| warning: false

library(tidyverse)
library(exscidata)

Oppgave15 <- strengthvolume %>%
  filter(exercise %in% c("isom", "isok.60", "isok.120", "isok.240"),
         !is.na(load)) %>%
  mutate(velocity = case_when(
    exercise == "isom" ~ 0,
    exercise == "isok.60" ~ 60,
    exercise == "isok.120" ~ 120,
    exercise == "isok.240" ~ 240
  )) %>%
  ggplot(aes(x = velocity, y = load, color = sex)) +
  geom_smooth(method = "lm", se = TRUE) +
  facet_wrap(~ time)

Oppgave15
```

Oppgave 16

```{r}
#| echo: true
#| message: false
#| warning: false

library(tidyverse)
library(exscidata)

Oppgave16a <- millward %>% 
  pivot_longer(c(RNA, protein_synthesis), names_to = "variabel",
               values_to = "verdi") %>% 
  ggplot(aes(x = verdi)) +
  geom_histogram(bins = 20, fill = "red", color = "black") +
  facet_wrap(~ variabel, scales = "free_x") +
  theme_minimal() +
  labs(
    title = "fordelinger: RNA og proteinsyntese",
    x = "µg/mg protein",
    y = "Antall"
  )

Oppgave16a


```
